### ISSUE TITLE
update webxdc.js and webxdc.d.ts

### ISSUE THREAD

**Issue by adbenitez** [webxdc/hello#45]
with the addition of the new import/export API the webxdc.js file that serves as a simple emulator needs to be updated

related: https://support.delta.chat/t/planned-webxdc-apis-for-processing-files/2570

once webxdc.js is updated here, it should go to at least the webxdc-test and calendar repos.

**Comment by Simon-Laux** [comment]
prior work:

https://github.com/webxdc/webxdc_docs/pull/44 contains types (not updated to newest api (move from `File` to just base64) as of today, so needs to wait a bit or also update there)

https://github.com/webxdc/calendar/pull/11 contains an updated simulator for import (api not settled 100% yet) and export (still `File`). So it can serve as a base for working on this issue.

**Comment by Pay82** [comment]
> with the addition of the new import/export API the webxdc.js file that serves as a simple emulator needs to be updated
> 
> 
> 
> related: https://support.delta.chat/t/planned-webxdc-apis-for-processing-files/2570
> 
> 
> 
> once webxdc.js is updated here, it should go to at least the webxdc-test and calendar repos.

Q

**Comment by ralphtheninja** [comment]
I blocked the spammer.

**Comment by r10s** [comment]
> I blocked the spammer.

?

i think, i missed sth :)

**Comment by ralphtheninja** [comment]
> i think, i missed sth :)

Some random user made random junk posts and the post got deleted after I reported them. All is good. @r10s Feel free to continue your spamming ;)

**Comment by r10s** [comment]
thanks for explanation!

/me yum yum, spam
